In [32]:
#write a python program to convert an array to an ordinary list
#with the same items
#we can use the np.tolist() function.

    
import numpy as np

def nptolist(X):
    num_list = X.tolist()
    print(num_list)

    
X = np.array([[20, 28, 29], [22, 18, 13], [23, 21, 18], [5, 17, 24], [9, 20, 6]])

nptolist(X)




[[20, 28, 29], [22, 18, 13], [23, 21, 18], [5, 17, 24], [9, 20, 6]]


In [26]:
#write a NumPy program to compute the sum of diagonal elements
#of a given array
#Hint: two methods to solve this problem:
#1. manually(without direct function)
#2. using the trace function


import numpy as np

X = np.array([[20, 28, 29], [22, 18, 13], [23, 21,18]])

#
diag = np.diagonal(X)

print(X)

print("the diagonal is", diag)


print(sum(diag))




[[20 28 29]
 [22 18 13]
 [23 21 18]]
the diagonal is [20 18 18]
56


In [33]:
#given an array of your choice
#get all values higher than X:
#if a = [[1,2],[3,5]] and X = 2 : then result is 3,5
#because they are higher than 2

import numpy as np

x = np.array([[20, 28, 29], [22, 18, 13], [23, 21, 18], [5, 17, 24], [9, 20, 6]])

print(x[x>13])

[20 28 29 22 18 23 21 18 17 24 20]


In [20]:
#given 2 arrays A & B have the same shape
#the task is to apply addition by hand:
#C is the new array

import numpy as np

A = np.array([[3,4,5],[1,6,4],[6,9,4]])

B = np.array([[2,5,4],[3,2,9],[6,3,8]])

C = A + B


print(C)





[[ 5  9  9]
 [ 4  8 13]
 [12 12 12]]


In [40]:
#write a NumPy program to subtract the mean
#of each row of a given matrix
#hint: use the mean function

import numpy as np

X = np.array([[24, 20, 27], [22, 19, 14], [24, 20,18], [5, 15, 35], [9, 35, 18]])

W = np.mean(X, axis=1)

Y = np.mean(X)

z = Y - W

z


array([-3.33333333,  2.        , -0.33333333,  2.        , -0.33333333])